
package GUI;

/**
 *
 * @author JoseGarita
 */
public class borradoDeNotas extends javax.swing.JFrame {

    /**
     * Creates new form borradoDeNotas
     */
    public borradoDeNotas() {
        initComponents();
        grupo1.add(radPersonaFisica);
        grupo1.add(radPersonaJuridica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        radPersonaFisica = new javax.swing.JRadioButton();
        radPersonaJuridica = new javax.swing.JRadioButton();
        textIdPersona = new javax.swing.JTextField();
        texIdtNota = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radPersonaFisica.setText("Persona fisica");

        radPersonaJuridica.setText("Persona Juridica");

        textIdPersona.setText("idPersona");
        textIdPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textIdPersonaMouseClicked(evt);
            }
        });

        texIdtNota.setText("Nota desea borrar");
        texIdtNota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                texIdtNotaMouseClicked(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBorrar)
                        .addComponent(textIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(texIdtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radPersonaFisica)
                    .addComponent(radPersonaJuridica))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radPersonaFisica)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(textIdPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radPersonaJuridica)
                    .addComponent(texIdtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>                        

    private void textIdPersonaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        textIdPersona.setText("");        // TODO add your handling code here:
    }                                          

    private void texIdtNotaMouseClicked(java.awt.event.MouseEvent evt) {                                        
        texIdtNota.setText("");
    }                                       

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {                                       
       this.dispose();
       lobbyUsuario.main(null);
    }                                      

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {                                       
      try{
          if(radPersonaJuridica.isSelected())
            logica.logicaBorradoDatos.borrarDatos(1, _NombreUsuario, textIdPersona.getText(), texIdtNota.getText());       
          if(radPersonaFisica.isSelected())
              logica.logicaBorradoDatos.borrarDatos(2, _NombreUsuario, textIdPersona.getText(), texIdtNota.getText());       
      }
      catch(ClassNotFoundException e){
      
      }
    }                                      

    /**
     * @param args the command line arguments
     * @param pNombreUsuario
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borradoDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borradoDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borradoDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borradoDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borradoDeNotas().setVisible(true);
            }
        });
    }
    public static void setUsuario(String pUsuario){
        _NombreUsuario = pUsuario;
    }
    static private String _NombreUsuario;
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JRadioButton radPersonaFisica;
    private javax.swing.JRadioButton radPersonaJuridica;
    private javax.swing.JTextField texIdtNota;
    private javax.swing.JTextField textIdPersona;
    // End of variables declaration                   
}
